import React from 'react';
import styles from './page.module.css';

const ApiDocsPage = () => {
  return (
    <div className={styles.container}>
      <h1>Backend API Expectations</h1>
      <p>This document outlines the API endpoints that the frontend expects from the backend server, typically running at <code>http://127.0.0.1:8100</code>.</p>
      <hr />

      <h2>1. <code>GET /current_board</code></h2>
      <ul>
        <li><strong>Purpose:</strong> Fetches the current visual state of the chessboard.</li>
        <li><strong>Expected Response:</strong>
          <ul>
            <li><strong>Content-Type:</strong> <code>image/svg+xml</code> or <code>text/plain</code></li>
            <li><strong>Body:</strong> The raw SVG content as a string. This SVG should represent the current board state.</li>
          </ul>
        </li>
      </ul>
      <hr />

      <h2>2. <code>GET /debug_images</code></h2>
      <ul>
        <li><strong>Purpose:</strong> Fetches a list of paths to debug images generated by the backend.</li>
        <li><strong>Expected Response:</strong>
          <ul>
            <li><strong>Content-Type:</strong> <code>application/json</code></li>
            <li><strong>Body:</strong> A JSON object with an <code>images</code> key, whose value is an array of strings. Each string is a URL path (relative to the backend's base URL) to a debug image.</li>
          </ul>
          <pre><code>
{/* {
  "images": [
    "/path/to/debug_image_1.jpg",
    "/path/to/debug_image_2.png",
    "/another/path/image.webp"
  ]
} */}
          </code></pre>
        </li>
      </ul>
      <hr />

      <h2>3. <code>GET /&lt;image_path&gt;</code> (e.g., <code>/images/debug_image_1.jpg</code>)</h2>
      <ul>
        <li><strong>Purpose:</strong> Serves an individual debug image based on the path provided by <code>/debug_images</code>.</li>
        <li><strong>Expected Response:</strong>
          <ul>
            <li><strong>Content-Type:</strong> Appropriate image content type (e.g., <code>image/jpeg</code>, <code>image/png</code>, <code>image/webp</code>)</li>
            <li><strong>Body:</strong> The raw binary data of the image file.</li>
          </ul>
        </li>
      </ul>
      <hr />

      <h2>4. <code>POST /predict</code></h2>
      <ul>
        <li><strong>Purpose:</strong> Submits an image of a chessboard for analysis and prediction of its state.</li>
        <li><strong>Expected Request:</strong>
          <ul>
            <li><strong>Content-Type:</strong> <code>multipart/form-data</code></li>
            <li><strong>Body:</strong>
              <ul>
                <li><code>image</code>: The image file of the chessboard.</li>
                <li><code>a1_pos</code>: A string indicating the position of the 'a1' square on the board (e.g., "bottom-left", "top-right").</li>
              </ul>
            </li>
          </ul>
        </li>
        <li><strong>Expected Response:</strong>
          <ul>
            <li><strong>Content-Type:</strong> <code>application/json</code></li>
            <li><strong>Body:</strong> A JSON object containing the predicted FEN, an ASCII representation of the board, and an SVG of the board.</li>
          </ul>
          <pre><code>
{/* {
  "fen": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
  "board_ascii": "+---+---+---+---+---+---+---+---\n| r | n | b | q | k | b | n | r |\n+---+---+---+---+---+---+---+---\n| p | p | p | p | p | p | p | p |\n+---+---+---+---+---+---+---+---\n|   |   |   |   |   |   |   |   |\n+---+---+---+---+---+---+---+---\n|   |   |   |   |   |   |   |   |\n+---+---+---+---+---+---+---+---\n|   |   |   |   |   |   |   |   |\n+---+---+---+---+---+---+---+---\n|   |   |   |   |   |   |   |   |\n+---+---+---+---+---+---+---+---\n| P | P | P | P | P | P | P | P |\n+---+---+---+---+---+---+---+---\n| R | N | B | Q | K | B | N | R |\n+---+---+---+---+---+---+---+---",
  "board_svg": "&lt;svg&gt;...&lt;/svg&gt;"
} */}
          </code></pre>
        </li>
      </ul>
      <hr />

      <h2>5. <code>GET /nextmove</code></h2>
      <ul>
        <li><strong>Purpose:</strong> Requests the chess engine to compute and return the next best move based on the current board state.</li>
        <li><strong>Expected Response:</strong>
          <ul>
            <li><strong>Content-Type:</strong> <code>application/json</code></li>
            <li><strong>Body:</strong> A JSON object detailing the best move, the new FEN after the move, and an SVG of the board with the move highlighted.</li>
          </ul>
          <pre><code>
{/* {
  "best_move": {
    "uci": "e2e4",
    "san": "e4",
    "score": "+0.5"  // Optional: engine's evaluation score
  },
  "new_fen": "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1",
  "board_svg_with_move": "&lt;svg&gt;...&lt;/svg&gt;" // SVG highlighting the move
} */}
          </code></pre>
        </li>
      </ul>
      <hr />

      <h2>6. <code>POST /set_elo</code></h2>
      <ul>
        <li><strong>Purpose:</strong> Sets the ELO rating for the chess engine, influencing its playing strength.</li>
        <li><strong>Expected Request:</strong>
          <ul>
            <li><strong>Content-Type:</strong> <code>application/json</code></li>
            <li><strong>Body:</strong> A JSON object containing the desired ELO rating.</li>
          </ul>
          <pre><code>
{/* {
  "elo": 1500
} */}
          </code></pre>
        </li>
        <li><strong>Expected Response:</strong>
          <ul>
            <li><strong>Content-Type:</strong> <code>application/json</code></li>
            <li><strong>Body:</strong> A JSON response confirming the ELO setting or indicating an error.</li>
          </ul>
          <pre><code>
{/* {
  "message": "ELO set to 1500"
} */}
          </code></pre>
        </li>
      </ul>
      <hr />

      <h2>7. <code>GET /visualize_next_move</code></h2>
      <ul>
        <li><strong>Purpose:</strong> Fetches a visualization (e.g., an SVG) that illustrates the engine's thought process or potential next moves.</li>
        <li><strong>Expected Response:</strong>
          <ul>
            <li><strong>Content-Type:</strong> <code>image/svg+xml</code> or <code>text/plain</code></li>
            <li><strong>Body:</strong> The raw SVG content as a string.</li>
          </ul>
        </li>
      </ul>
      <hr />

      <h2>8. <code>GET /</code></h2>
      <ul>
        <li><strong>Purpose:</strong> A basic health check endpoint to determine if the backend server is operational.</li>
        <li><strong>Expected Response:</strong>
          <ul>
            <li>Any successful HTTP status code (e.g., <code>200 OK</code>). The content of the response body is not strictly defined but can be empty or a simple status message.</li>
          </ul>
        </li>
      </ul>
      <hr />

      <h2>9. Agent Communication (Proxied via Next.js API Routes)</h2>
      <p>These endpoints are handled by Next.js API routes (<code>/api/agent</code>) which then proxy requests to a separate agent system (e.g., <code>http://localhost:8000</code>). The frontend does not directly call the agent system.</p>

      <h3><code>POST /api/agent</code> (for <code>initializeSession</code>)</h3>
      <ul>
        <li><strong>Purpose:</strong> Initializes a session with the agent system.</li>
        <li><strong>Expected Request (to Next.js proxy):</strong>
          <ul>
            <li><strong>Content-Type:</strong> <code>application/json</code></li>
            <li><strong>Body:</strong>
              <pre><code>
{/* {
  "app_name": "string",
  "user_id": "string",
  "session_id": "string",
  "action": "initialize"
} */}
              </code></pre>
            </li>
          </ul>
        </li>
        <li><strong>Expected Response (from Next.js proxy):</strong>
          <ul>
            <li><strong>Content-Type:</strong> <code>application/json</code></li>
            <li><strong>Body:</strong> A JSON object indicating success or failure of the initialization.</li>
          </ul>
        </li>
      </ul>

      <h3><code>POST /api/agent</code> (for <code>sendToAgent</code>)</h3>
      <ul>
        <li><strong>Purpose:</strong> Sends a message to the agent system and receives a response.</li>
        <li><strong>Expected Request (to Next.js proxy):</strong>
          <ul>
            <li><strong>Content-Type:</strong> <code>application/json</code></li>
            <li><strong>Body:</strong>
              <pre><code>
{/* {
  "app_name": "string",
  "user_id": "string",
  "session_id": "string",
  "new_message": {
    "role": "user" | "assistant",
    "parts": [
      {
        "text": "string"
      }
    ]
  }
} */}
              </code></pre>
            </li>
          </ul>
        </li>
        <li><strong>Expected Response (from Next.js proxy):</strong>
          <ul>
            <li><strong>Content-Type:</strong> <code>application/json</code></li>
            <li><strong>Body:</strong> A JSON object containing the agent's response.</li>
          </ul>
          <pre><code>
{/* {
  "response": "string",
  "agent": "string",
  "confidence": "number", // Optional
  "metadata": {}
} */}
          </code></pre>
        </li>
      </ul>
    </div>
  );
};

export default ApiDocsPage;